#!/usr/bin/env perl
use common::sense;
use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);
use Pod::Usage;
use File::Find;


sub usage () {
    pod2usage(-verbose => 1);
}


my $follow_symlinks = 0;
my $needhelp;
GetOptions(
    'h|help' => \$needhelp,
    'l|follow-symlinks' => \$follow_symlinks,
) or usage;
usage if $needhelp;


my @dirs = @ARGV ? @ARGV : (".");
@dirs = grep {
    -d || do {
        print STDERR "$_: $!\n";
        0;
    };
} @dirs;


find({
    wanted => sub {
        warn "hi: $_";
    },
    follow => $follow_symlinks,
    no_chdir => 1,
}, @dirs);


__END__

=head1 NAME

    weavel - unlink and link duplicated files


=head1 SYNOPSIS


=head1 OPTIONS

=over

=item -h, --help

Show this help.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>
