#!/usr/bin/env perl
use common::sense;
use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);
use Pod::Usage;


sub usage () {
    pod2usage(-verbose => 1);
}


my $needhelp;
GetOptions(
    'h|help' => \$needhelp,
) or usage;
usage if $needhelp;




__END__

=head1 NAME

    weavel - unlink and link duplicated files


=head1 SYNOPSIS


=head1 OPTIONS

=over

=item -h, --help

Show this help.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>
