#!/usr/bin/env perl
use common::sense;
use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);
use Pod::Usage;
use File::Find;
use Data::Dumper;
use Readonly;



Readonly::Scalar my $ST_COMPARE => 0;
Readonly::Scalar my $ST_HASH    => 1;



sub usage () {
    pod2usage(-verbose => 1);
}

sub uneval {
    local $Data::Dumper::Terse = 1;
    local $Data::Dumper::Indent = 1;
    Dumper(@_);
}

{
    my $verbose = 0;

    sub set_verbose {
        $verbose = shift;
    }

    sub verbose {
        $verbose and say STDERR "[verbose] ", @_;
    }
}

sub compare_two_directories {
    my ($dir1, $dir2, $check_directory, $follow_symlinks) = @_;
    find({
        wanted => sub {
            return if !$check_directory && -d $_;
            verbose "processing $_...";
        },
        follow => $follow_symlinks,
        no_chdir => 1,
    }, $dir1);
}


my $verbose = 0;
my $follow_symlinks = 0;
my $check_directory = 0;
my $stragegy = $ST_COMPARE;
my $needhelp;
GetOptions(
    'h|help' => \$needhelp,
    'l|follow-symlinks' => \$follow_symlinks,
    'd|directory' => \$check_directory,
    'v|verbose' => \$verbose,
    'compare' => sub { $stragegy = $ST_COMPARE },
    'hash' => sub { $stragegy = $ST_HASH },
) or usage;
usage if $needhelp;
set_verbose $verbose;


my @dirs = @ARGV ? @ARGV : (".");
@dirs = grep {
    -d || do {
        print STDERR "$_: $!\n";
        0;
    };
} @dirs;
verbose '@dirs = ' . uneval(\@dirs);


if ($stragegy == $ST_COMPARE) {
    unless (@ARGV == 2) {
        say STDERR "specify two directories.";
        usage;
    }
    compare_two_directories(@ARGV, $check_directory, $follow_symlinks);
}
elsif ($stragegy == $ST_HASH) {
    die "not implemented.";    # TODO
}
else {
    die "must not reach here!\n";
}


__END__

=head1 NAME

    weavel - unlink and link duplicated files


=head1 SYNOPSIS


=head1 OPTIONS

=over

=item -h, --help

Show this help.

=back


=head1 AUTHOR

tyru <tyru.exe@gmail.com>
